version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm run test
